/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef thrift_test_kernal_CONSTANTS_H
#define thrift_test_kernal_CONSTANTS_H

#include "thrift_test_kernal_types.h"

namespace thrift_test_kernal {

class thrift_test_kernalConstants {
 public:
  thrift_test_kernalConstants();

  int32_t MAX;
};

extern const thrift_test_kernalConstants g_thrift_test_kernal_constants;

} // namespace

#endif
