/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hotspot_api_CONSTANTS_H
#define hotspot_api_CONSTANTS_H

#include "hotspot_api_types.h"

namespace hotspot { namespace service {

class hotspot_apiConstants {
 public:
  hotspot_apiConstants();

};

extern const hotspot_apiConstants g_hotspot_api_constants;

}} // namespace

#endif
