/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hotspot_api_constants.h"

namespace hotspot { namespace service {

const hotspot_apiConstants g_hotspot_api_constants;

hotspot_apiConstants::hotspot_apiConstants() {
}

}} // namespace

