/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calculate_CONSTANTS_H
#define calculate_CONSTANTS_H

#include "calculate_types.h"

namespace calculator {

class calculateConstants {
 public:
  calculateConstants();

};

extern const calculateConstants g_calculate_constants;

} // namespace

#endif
