/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calculate_constants.h"

namespace calculator {

const calculateConstants g_calculate_constants;

calculateConstants::calculateConstants() {
}

} // namespace

