
//This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ThriftTestKernalService.h"
#include "ThriftTestKernalServiceHandler.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include "simple_log.h"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::thrift_test_kernal;

void ThriftTestKernalServiceHandler::GetServiceList(GetServiceListResponse& _return, const GetServiceListRequest& request) {
	// Your implementation goes here
	log_info("GetServiceList");
}

void ThriftTestKernalServiceHandler::AddService(AddServiceResponse& _return, const AddServiceRequest& request) {
	// Your implementation goes here
	log_info("AddService");
}

void ThriftTestKernalServiceHandler::FillData(FillDataResponse& _return, const FillDataRequest& request) {
	// Your implementation goes here
	log_info("FillData");
}

void ThriftTestKernalServiceHandler::RequestTrigger(RequestTriggerReseponse& _return, const RequestTriggerRequest& request) {
	// Your implementation goes here
	log_info("RequestTrigger");
}

