/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "thrift_test_kernel_constants.h"

namespace thrift_test_kernel {

const thrift_test_kernelConstants g_thrift_test_kernel_constants;

thrift_test_kernelConstants::thrift_test_kernelConstants() {
  MAX = 3;

}

} // namespace

