/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef thrift_test_kernel_CONSTANTS_H
#define thrift_test_kernel_CONSTANTS_H

#include "thrift_test_kernel_types.h"

namespace thrift_test_kernel {

class thrift_test_kernelConstants {
 public:
  thrift_test_kernelConstants();

  int32_t MAX;
};

extern const thrift_test_kernelConstants g_thrift_test_kernel_constants;

} // namespace

#endif
