/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "thrift_test_kernal_constants.h"

namespace thrift_test_kernal {

const thrift_test_kernalConstants g_thrift_test_kernal_constants;

thrift_test_kernalConstants::thrift_test_kernalConstants() {
  MAX = 3;

}

} // namespace

