INCLUDE = -I ./	\
		  -I ./util	\
		  -I ./main 	\
		  -I ./thirdparty/simple-log/include/	\
		  -I ./thirdparty/simple-server/include/ 	

LIB = ./thirdparty/simple-log/lib/libsimplelog.a	\
	  ./thirdparty/simple-server/lib/libsimpleserver.a


